main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('catalog', views.CatalogView.as_view(), name='catalog'),
    path('catalog/<str:type>', views.CatalogView.as_view(), name='catalog'),
    path('catalog/item/<int:pk>', views.SingleItemView.as_view(), name='catalog-item'),
    path('services', views.ServicesListView.as_view(), name='services'),
    path('services/<str:type>', views.ServiceItemDetail.as_view(), name='services-item'),
    path('contacts', views.ContactsView.as_view(), name='contacts'),
    path('mail', views.mail, name='mail'),
]

reroomDjango/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import os
import random
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType


class SingleInstanceOnly(object):
    def save(self, *args, **kwargs):
        if self.__class__.objects.exists() and not self.pk:
            raise ValidationError(
                f'Вы не можете дважды добавить объект {self._meta.verbose_name}, просто редактируйте предыдущий')
        return super(SingleInstanceOnly, self).save(*args, **kwargs)


# FIXME: refactor this shit
class IndexPage(SingleInstanceOnly, models.Model):
    UPLOAD_TO = os.path.join('admin', 'index')

    class Meta:
        verbose_name = 'Главная страница'
        verbose_name_plural = 'Главная страница'

    learn_more_text = models.CharField(max_length=1000, verbose_name='Текст для кнопки узнать больше')
    first_heading = models.CharField(max_length=1000, verbose_name='Заголовок на главной странице')
    first_image = models.ImageField(verbose_name='Картинка, отображающаяся на главной странице', blank=True,
                                    upload_to=UPLOAD_TO)
    down_text = models.CharField(max_length=100, verbose_name='Текст "Вниз"')
    second_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок второго экрана')
    second_screen_image = models.ImageField(verbose_name='Картинка второго экрана', blank=True)
    second_screen_descr = models.TextField(max_length=1000, verbose_name='Описание второго экрана')
    third_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок третьего экрана')
    third_screen_image = models.ImageField(verbose_name='Картинка третьего экрана', blank=True, upload_to=UPLOAD_TO)
    third_screen_descr = models.TextField(max_length=1000, verbose_name='Описание третьего экрана')
    fourth_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок четвертого экрана')
    fourth_screen_image = models.ImageField(verbose_name='Картинка четвертого экрана', blank=True, upload_to=UPLOAD_TO)
    fourth_screen_descr = models.TextField(max_length=1000, verbose_name='Описание четвертого экрана')
    fifth_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок пятого экрана')
    fifth_screen_image = models.ImageField(verbose_name='Картинка пятого экрана', blank=True, upload_to=UPLOAD_TO)
    fifth_screen_descr = models.TextField(max_length=1000, verbose_name='Описание пятого экрана')
    sixth_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок шестого экрана')
    seventh_screen_form_heading = models.CharField(max_length=1000, verbose_name='Заголовок формы')
    seventh_screen_form_button_text = models.CharField(max_length=1000, verbose_name='Текст в кнопке отправить')

    def __str__(self):
        return 'Главная страница'


class ContactsPage(SingleInstanceOnly, models.Model):
    title = models.CharField(max_length=50, verbose_name='title страницы')
    heading = models.TextField(verbose_name='Заголовок на первом экране')
    company_name_heading = models.TextField(verbose_name='Заголовок названия компании')
    addr_heading = models.TextField(verbose_name='Заголовок адреса')
    phone_heading = models.TextField(verbose_name='Заголовок телефона')
    working_time_heading = models.TextField(verbose_name='Заголовок время работы')
    email_heading = models.TextField(verbose_name='Заголовок email')
    form_heading = models.TextField(verbose_name='Заголовок над формой')
    submit_text = models.TextField(verbose_name='Текст в кнопке формы')

    class Meta:
        verbose_name = 'Страница контакты'
        verbose_name_plural = 'Страница контакты'

    def __str__(self):
        return 'Страница Контакты'


class ContactInfo(SingleInstanceOnly, models.Model):
    company_name = models.CharField(max_length=500, verbose_name='Название компании')
    phone = models.CharField(max_length=50, verbose_name='Телефон')
    email = models.CharField(max_length=100, verbose_name='E-mail')
    addr = models.CharField(max_length=500, verbose_name='Адрес')
    working_time = models.CharField(max_length=500, verbose_name='Часы работы')
    instagram_text = models.CharField(max_length=500, verbose_name='Текст instagram')
    instagram_link = models.URLField(max_length=500, verbose_name='Ссылка на аккаунт в instagram')
    development = models.CharField(max_length=500, verbose_name='Компания разработчик')

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return 'Контакты'


class ProjectsPage(SingleInstanceOnly, models.Model):
    services_page_title = models.CharField(max_length=200, verbose_name='Заголовок страницы Projects')
    single_item_top_left_heading = models.CharField(max_length=500, verbose_name='Заголовок в левом верхнем углу')
    single_item_top_right_heading = models.CharField(max_length=500, verbose_name='Заголовок в правом верхнем углу')
    single_item_bottom_left_heading = models.CharField(max_length=500, verbose_name='Заголовок в левом нижнем углу')
    single_item_bottom_right_heading = models.CharField(max_length=500, verbose_name='Заголовок в правом нижнем углу')

    class Meta:
        verbose_name = 'Страница Projects'
        verbose_name_plural = 'Страница Projects'

    def __str__(self):
        return 'Страница проекты'

    def get_random_catalog_items(self, number_of_items):
        return random.sample(list(self.catalogitem_set.filter(show_on_main=True)), number_of_items)


class CatalogItem(models.Model):
    UPLOAD_TO = os.path.join('admin', 'services')

    SERVICE_TYPES = (
        ('design', 'Дизайн'),
        ('house', 'Ремонт квартир и домов'),
        ('office', 'Ремонт офисов'),
        ('construction', 'Строительство домов'),
    )

    service = models.ForeignKey('ProjectsPage', on_delete=models.CASCADE, blank=True)
    show_on_main = models.BooleanField(default=False, verbose_name='Показывать на главной')
    name = models.CharField(max_length=500, verbose_name='Имя')
    type = models.CharField(max_length=80, choices=SERVICE_TYPES, verbose_name='Тип проекта')
    main_img = models.ImageField(upload_to=UPLOAD_TO, blank=True, verbose_name='Главное изображение')
    top_left = models.CharField(max_length=500, verbose_name='Текст в левом верхнем углу')
    top_right = models.CharField(max_length=500, verbose_name='Текст в правом верхнем углу')
    bottom_left = models.CharField(max_length=500, verbose_name='Текст в левом нижнем углу')
    bottom_right = models.CharField(max_length=500, verbose_name='Текст в правом нижнем углу')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def get_absolute_url(self):
        return reverse('main:catalog-item', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.name} - {self.type}'


class CatalogItemImg(models.Model):
    image_field = models.ImageField(upload_to=CatalogItem.UPLOAD_TO, blank=True,
                                    verbose_name='Маленькая картинка на странице services')
    catalog_item = models.ForeignKey('CatalogItem', on_delete=models.CASCADE, blank=False,
                                     verbose_name='Объекты из каталога')
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Картинка айтема каталога'
        verbose_name_plural = 'Картинки айтемов каталога'


class ServicesPage(models.Model):
    title = models.CharField(max_length=500, verbose_name='title')
    heading = models.TextField(max_length=500, verbose_name='Заголовок')
    text_block_left = models.TextField(max_length=1500, verbose_name='Текстовый блок слева')
    text_block_right = models.TextField(max_length=1500, verbose_name='Текстовый блок справа')

    class Meta:
        verbose_name = 'Страница услуги'
        verbose_name_plural = 'Страница услуги'

    def __str__(self):
        return 'Страница сервисы'


class ServicesItem(models.Model):
    SERVICE_TYPE = [
        ['design', 'Дизайн'],
        ['house repair', 'Ремонт квартир и домов'],
        ['office repair', 'Ремонт офисов'],
        ['construction', 'Строительство домов'],
    ]

    UPLOAD_TO = os.path.join('admin', 'index', 'services')

    type = models.CharField(max_length=150, choices=SERVICE_TYPE, verbose_name='Тип услуги')
    name = models.TextField(max_length=500, verbose_name='Название')
    preview_img = models.ImageField(upload_to=UPLOAD_TO, blank=True, verbose_name='Картинка превью')
    main_img = models.ImageField(upload_to=UPLOAD_TO, blank=True, verbose_name='Главная картинка')
    image_text = models.TextField(max_length=500, verbose_name='Текст на картинке')
    projects = models.ManyToManyField('CatalogItem', blank=True, verbose_name='Проекты')
    headings_with_text_blocks = models.ManyToManyField('HeadingAndText', blank=True,
                                                       verbose_name='Заголовки и текст')
    accordion = models.ForeignKey('ServiceItemAccordion', blank=True, on_delete=models.DO_NOTHING,
                                  verbose_name='Аккордион')

    class Meta:
        verbose_name_plural = 'Айтемы услуг'
        verbose_name = 'Айтем услуг'

    def check_enough_headings(self, num):
        print(self.headings_with_text_blocks.count())
        if self.headings_with_text_blocks.count() < num:
            raise ValidationError(
                f'Недостаточно заголовков с текстом для сохранения, добавьте как минимум {num} заголовоков')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:services-item', kwargs={'type': self.type})

    # Можно создать только один инстанс с типом Дизайн/Ремонт квартир/Ремонт офисов etc.
    def save(self, *args, **kwargs):

main/views.py
from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
import json
from django.http import HttpResponse
from django.template.context_processors import csrf
from . import models
from django.views.generic import DetailView, ListView
from . import mixins


# Create your views here.
def index(request):
    context = {
        'index_page': models.IndexPage.objects.first(),
        'contact': models.ContactInfo.objects.first(),
        'service_objects': models.ProjectsPage.objects.first().get_random_catalog_items(3)
    }
    context.update(csrf(request))
    return render_to_response('main/index.html', context=context)


def about(request):
    return render_to_response('main/about.html')


class CatalogView(mixins.ContactInfoMixin, ListView):
    model = models.CatalogItem
    template_name = 'main/catalog.html'
    context_object_name = 'catalog_items'

    def get_queryset(self):
        if 'type' in self.kwargs:
            return get_list_or_404(models.CatalogItem, type=self.kwargs['type'])
        return models.CatalogItem.objects.all()


class ServicesListView(mixins.ContactInfoMixin, ListView):
    model = models.ServicesItem
    template_name = 'main/services_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ServicesListView, self).get_context_data(**kwargs)
        context['services_page'] = models.ServicesPage.objects.first()
        return context


class ServiceItemDetail(mixins.ContactInfoMixin, DetailView):
    model = models.ServicesItem
    template_name = 'main/service_item.html'

    def get_object(self, queryset=None):
        if 'type' in self.kwargs:
            return get_object_or_404(models.ServicesItem, type=self.kwargs['type'])


class ContactsView(mixins.ContactInfoMixin, DetailView):
    model = models.ContactsPage
    template_name = 'main/contacts.html'

    def get_object(self, queryset=None):
        return self.model.objects.first()


class SingleItemView(mixins.ContactInfoMixin, DetailView):
    model = models.CatalogItem
    context_object_name = 'catalog_item'
    template_name = 'main/catalog_item.html'

    def get_context_data(self, **kwargs):
        context = super(SingleItemView, self).get_context_data(**kwargs)
        return context


def mail(request):
    if request.method == 'POST' and request.is_ajax():
        return HttpResponse(json.dumps({'success': 'true'}), content_type="application/json")

main/templates/main/catalog_item.html
{% extends 'main/layout.html' %}
{% load static %}

{% block body %}

    <div class="wrapper">
        {% include 'main/includes/header.html' %}
        {% include 'main/includes/menu.html' %}

        <div class="p-projects-details">


            <div class="pd-panel pd-panel--closed">
                <div class="pd-panel-head">
                    <a class="pd-panel-head__all" href="{% url 'main:catalog' %}">
                        <i class="icon-all-projects"></i>
                        <span>все проекты</span>
                    </a>
                    <button class="pd-panel-head__info" type="button">
                        <i class="icon-close"></i>
                        <span>инфо</span>
                    </button>
                </div>
                <div class="pd-panel-body">
                    <div class="pd-panel-body__inner">
                        <div class="pd-panel-body__control">
                            <a href="https://salazckin.github.io/third/catalog" title="Все проекты">
                                <i class="icon-all-projects"></i>
                            </a>
                            <button data-pdslider-arr="next" type="button">
                                <i class="icon-arrow-right"></i>
                            </button>
                            <button data-pdslider-arr="prev" type="button">
                                <i class="icon-arrow-left"></i>
                            </button>
                        </div>
                        <h1 class="pd-panel-body__title h2-like">{{ catalog_item.name }}</h1>
                        <ul class="pd-panel-body__list">
                            <li class="pd-row">
                                <div class="pr-row__icon">
                                    <i class="icon-date"></i>
                                </div>
                                <div class="pd-row__info">
                                    <div class="pd-row__key">Дата</div>
                                    <div class="pd-row__value">{{ catalog_item.top_left }}</div>
                                </div>
                            </li>
                            <li class="pd-row">
                                <div class="pr-row__icon">
                                    <i class="icon-address"></i>
                                </div>
                                <div class="pd-row__info">
                                    <div class="pd-row__key">Адрес</div>
                                    <div class="pd-row__value">{{ catalog_item.top_right }}</div>
                                </div>
                            </li>
                            <li class="pd-row">
                                <div class="pr-row__icon">
                                    <i class="icon-architect"></i>
                                </div>
                                <div class="pd-row__info">
                                    <div class="pd-row__key">Архитектор</div>
                                    <div class="pd-row__value">{{ catalog_item.bottom_left }}</div>
                                </div>
                            </li>
                            <li class="pd-row">
                                <div class="pr-row__icon">
                                    <i class="icon-photographer"></i>
                                </div>
                                <div class="pd-row__info">
                                    <div class="pd-row__key">Фотограф</div>
                                    <div class="pd-row__value">{{ catalog_item.bottom_right }}</div>
                                </div>
                            </li>
                        </ul>
                        <div class="pd-panel-body__gallery">
                            <div class="fraction">
                                <button class="fraction__arrow" data-pdslider-arr="prev" type="button">
                                    <i class="icon-arrow-left"></i>
                                </button>

                                <div class="fraction__info">
                                    <div class="fraction__nums">
                                        <span class="fraction__current">1</span>
                                        <span class="fraction__separ">/</span>
                                        <span class="fraction__max">9</span>
                                    </div>
                                    <div class="fraction__caption">фотогалерея</div>
                                </div>

                                <button class="fraction__arrow" data-pdslider-arr="next" type="button">
                                    <i class="icon-arrow-right"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="pd-slider">
                {% for catalog_item_img in catalog_item.catalogitemimg_set.all %}
                    <div class="pd-slider__slide">
                        <div class="slick-effect">
                            <img class="slick-effect__img" data-lazy="{{ catalog_item_img.image_field.url }}" alt=""/>
                        </div>
                    </div>
                {% endfor %}
            </div>


            <div class="pd-m-controls">
                <button type="button" data-pdslider-arr="prev">
                    <i class="icon-arrow-left"></i>
                </button>
                <a href="https://salazckin.github.io/third/catalog">
                    <i class="icon-all-projects"></i>
                </a>
                <button type="button" data-pdslider-arr="next">
                    <i class="icon-arrow-right"></i>
                </button>
            </div>

            <div class="pd-mcard">
                <div class="pd-mcard__inner">

                    <h1 class="pd-mcard__title h2-like">Квартира-студия</h1>
                    <ul class="pd-mcard__list">
                        <li class="pd-row">
                            <div class="pr-row__icon">
                                <i class="icon-date"></i>
                            </div>
                            <div class="pd-row__info">
                                <div class="pd-row__key">Дата</div>
                                <div class="pd-row__value">17.06.2017</div>
                            </div>
                        </li>
                        <li class="pd-row">
                            <div class="pr-row__icon">
                                <i class="icon-address"></i>
                            </div>
                            <div class="pd-row__info">
                                <div class="pd-row__key">Адрес</div>
                                <div class="pd-row__value">Москва, ул. Дурова 29</div>
                            </div>
                        </li>
                        <li class="pd-row">
                            <div class="pr-row__icon">
                                <i class="icon-architect"></i>
                            </div>
                            <div class="pd-row__info">
                                <div class="pd-row__key">Архитектор</div>
                                <div class="pd-row__value">Иван Иванов</div>
                            </div>
                        </li>
                        <li class="pd-row">
                            <div class="pr-row__icon">
                                <i class="icon-photographer"></i>
                            </div>
                            <div class="pd-row__info">
                                <div class="pd-row__key">Фотограф</div>
                                <div class="pd-row__value">Иван Иванов</div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

        </div>

        {% include 'main/includes/footer.html' %}
    </div>
{% endblock %}

main/templates/main/contacts.html
{% extends 'main/layout.html' %}
{% load static %}

{% block body %}

    <div class="wrapper">
        {% include 'main/includes/header.html' %}
        {% include 'main/includes/menu.html' %}

        <div class="p-contacts">
            <div class="page-head">
                <div class="page-head__inner container">
                    <h1 class="page-head__title">{{ object.heading }}</h1>
                </div>
            </div>
            <div class="block bg-white pb-sm">
                <div class="contacts-grid container-md mb-md">
                    <div class="row">
                        <div class="col-md-6">
                            <p>{{ object.company_name_heading }}
                                <br> {{ contact.company_name }}
                                <br>
                            </p>
                            <p>{{ object.addr_heading }}
                                <br> {{ contact.addr }}

                            </p>
                        </div>
                        <div class="col-md-6">
                            <p>
                            <div>{{ object.phone_heading }}</div>
                            <a href="tel:{{ contact.phone }}">{{ contact.phone }}</a>
                            </p>
                            <p>
                            <div>{{ object.working_time_heading }}</div>
                            <div>{{ contact.working_time }}</div>
                            </p>
                            <p>
                            <div>{{ object.email_heading }}</div>
                            <a href="{{ contact.email }}">{{ contact.email }}</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="map" id="map"></div>
                </div>
            </div>
            <div class="block">
                <div class="container-md mb-md">
                    <h2 class="text-center mb-lg">{{ object.form_heading }}</h2>
                    <form class="form" action="/feedback">
                        <div class="form__field-group">
                            <div class="form__field">
                                <input class="input-default" name="FullName" data-val="true" data-val-required
                                       type="text" placeholder="Представьтесь, пожалуйста">
                            </div>
                            <div class="form__field">
                                <input class="input-default" name="Email" data-val="true" data-val-required
                                       data-val-email type="email" placeholder="Ваш e-mail">
                            </div>
                            <div class="form__field">
                                <input class="input-default" name="Text" data-val="true" data-val-required type="text"
                                       placeholder="Ваш комментарий">
                            </div>
                        </div>
                        <button class="form__submit btn btn-status" type="submit">{{ object.submit_text }}</button>

                    </form>

                </div>
            </div>

        </div>

        {% include 'main/includes/footer.html' %}
    </div>

    <script src="https://maps.googleapis.com/maps/api/js?language=ru&key=AIzaSyAp8fJIR1ICTOzqhcKjWLR6Yl8h3U25OoY"></script>


{% endblock %}

main/templates/main/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="{% block html-class %}{% endblock %}" lang="ru">

<head prefix="og: http://ogp.me/ns#">
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link rel="stylesheet" href="{% static 'main/css/screen.min.css' %}">

    <script data-pace-options='{ "elements": false,"ajax": false,"restartOnPushState": false,"restartOnRequestAfter": false }'
            src="{% static 'main/js/pace.min.js' %}" defer></script>


</head>
<body>

{% block body %}

{% endblock %}

<script src="{% static 'main/js/bundle.min.js' %}"></script>
</body>
</html>

main/templates/main/service_item.html
{% extends 'main/layout.html' %}
{% load static %}
{% load reroom_template_tags %}

{% block body %}
    <div class="wrapper">
        {% include 'main/includes/header.html' %}
        {% include 'main/includes/menu.html' %}
        <div class="p-services-details">


            <div class="page-head">
                <div class="page-head__inner container">
                    <h1 class="page-head__title">{{ object.name }}</h1>
                </div>
            </div>
            <div class="block bg-white pb-sm static-content">
                <div class="container-md mb-md">
                    <div class="row row-grid-sm">
                        {% for heading_and_text in object.headings_with_text_blocks.all|slice:":2" %}
                            <div class="col-md-6">
                                <h2>{{ heading_and_text.heading }}</h2>

                                <p>{{ heading_and_text.text }}</p>

                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="container">
                    <div class="jumb jumb--sm"
                         style="background-image: url({{ object.main_img.url }});">
                        <div class="jumb__line"></div>
                        <div class="jumb__content">
                            <div class="h3-like">{{ object.image_text }}</div>
                        </div>
                        <div class="jumb__line"></div>
                    </div>
                </div>

            </div>
            <div class="block bg-white pb-sm static-content">
                <div class="container-md mb-md">
                    <div class="row row-grid-sm">
                        {% for chunk in object.headings_with_text_blocks.all|slice:"2:"|divide_by:2 %}
                            <div class="col-md-6">
                                {% for heading_and_text in chunk %}
                                    <h3>{{ heading_and_text.heading|safe }}</h3>

                                    <p>{{ heading_and_text.text|safe }}</p>

                                {% endfor %}
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
            <div class="block">
                <div class="container-md">
                    <div class="ddown-list-title">{{ object.accordion.title }}</div>
                    <div class="ddown-list">
                        {% for accordion_heading_with_text in object.accordion.items.all %}
                            <div class="ddown">
                                <div class="ddown-head">
                                    <div class="ddown-head__name">{{ accordion_heading_with_text.heading|safe }}</div>
                                    <div class="ddown-head__toggle">
                                        <div class="plus">
                                            <div class="plus__line-1"></div>
                                            <div class="plus__line-2"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="ddown-body">
                                    <div class="ddown-body__inner">
                                        <div class="static-content">
                                            {{ accordion_heading_with_text.text|safe }}

                                            {% if accordion_heading_with_text.images.exists %}

                                                <div class="slick">

                                                    {% for accordion_img in accordion_heading_with_text.images.all %}

                                                        <div class="slick__item">
                                                            <picture>
                                                                <source srcset="{{ accordion_img.img.url }}"
                                                                        type="image/png">
                                                                <img src="{{ accordion_img.img.url }}"
                                                                     alt="{{ accordion_img.img.heading }}"/>
                                                            </picture>
                                                        </div>

                                                    {% endfor %}

                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="block">
                <div class="container">

                    {% with object.projects.all as items %}
                        {% include 'main/includes/projects-stack.html' %}
                    {% endwith %}


                </div>
            </div>


        </div>

        {% include 'main/includes/footer.html' %}
    </div>
{% endblock %}