main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('catalog', views.CatalogView.as_view(), name='catalog'),
    path('catalog/<str:type>', views.CatalogView.as_view(), name='catalog'),
    path('catalog/item/<int:pk>', views.SingleItemView.as_view(), name='catalog-item'),
    path('services', views.ServicesListView.as_view(), name='services'),
    path('services/<str:type>', views.ServiceItemDetail.as_view(), name='services-item'),
    path('contacts', views.ContactsView.as_view(), name='contacts'),
    path('mail', views.mail, name='mail'),
]

reroomDjango/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import os
import random
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType


class SingleInstanceOnly(object):
    def save(self, *args, **kwargs):
        if self.__class__.objects.exists() and not self.pk:
            raise ValidationError(
                f'Вы не можете дважды добавить объект {self._meta.verbose_name}, просто редактируйте предыдущий')
        return super(SingleInstanceOnly, self).save(*args, **kwargs)


# FIXME: refactor this shit
class IndexPage(SingleInstanceOnly, models.Model):
    UPLOAD_TO = os.path.join('admin', 'index')

    class Meta:
        verbose_name = 'Главная страница'
        verbose_name_plural = 'Главная страница'

    learn_more_text = models.CharField(max_length=1000, verbose_name='Текст для кнопки узнать больше')
    first_heading = models.CharField(max_length=1000, verbose_name='Заголовок на главной странице')
    first_image = models.ImageField(verbose_name='Картинка, отображающаяся на главной странице', blank=True,
                                    upload_to=UPLOAD_TO)
    down_text = models.CharField(max_length=100, verbose_name='Текст "Вниз"')
    second_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок второго экрана')
    second_screen_image = models.ImageField(verbose_name='Картинка второго экрана', blank=True)
    second_screen_descr = models.TextField(max_length=1000, verbose_name='Описание второго экрана')
    third_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок третьего экрана')
    third_screen_image = models.ImageField(verbose_name='Картинка третьего экрана', blank=True, upload_to=UPLOAD_TO)
    third_screen_descr = models.TextField(max_length=1000, verbose_name='Описание третьего экрана')
    fourth_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок четвертого экрана')
    fourth_screen_image = models.ImageField(verbose_name='Картинка четвертого экрана', blank=True, upload_to=UPLOAD_TO)
    fourth_screen_descr = models.TextField(max_length=1000, verbose_name='Описание четвертого экрана')
    fifth_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок пятого экрана')
    fifth_screen_image = models.ImageField(verbose_name='Картинка пятого экрана', blank=True, upload_to=UPLOAD_TO)
    fifth_screen_descr = models.TextField(max_length=1000, verbose_name='Описание пятого экрана')
    sixth_screen_heading = models.TextField(max_length=1000, verbose_name='Заголовок шестого экрана')
    seventh_screen_form_heading = models.CharField(max_length=1000, verbose_name='Заголовок формы')
    seventh_screen_form_button_text = models.CharField(max_length=1000, verbose_name='Текст в кнопке отправить')

    def __str__(self):
        return 'Главная страница'


class ContactsPage(SingleInstanceOnly, models.Model):
    title = models.CharField(max_length=50, verbose_name='title страницы')
    heading = models.TextField(verbose_name='Заголовок на первом экране')
    company_name_heading = models.TextField(verbose_name='Заголовок названия компании')
    addr_heading = models.TextField(verbose_name='Заголовок адреса')
    phone_heading = models.TextField(verbose_name='Заголовок телефона')
    working_time_heading = models.TextField(verbose_name='Заголовок время работы')
    email_heading = models.TextField(verbose_name='Заголовок email')
    form_heading = models.TextField(verbose_name='Заголовок над формой')
    submit_text = models.TextField(verbose_name='Текст в кнопке формы')

    class Meta:
        verbose_name = 'Страница контакты'
        verbose_name_plural = 'Страница контакты'

    def __str__(self):
        return 'Страница Контакты'


class ContactInfo(SingleInstanceOnly, models.Model):
    company_name = models.CharField(max_length=500, verbose_name='Название компании')
    phone = models.CharField(max_length=50, verbose_name='Телефон')
    email = models.CharField(max_length=100, verbose_name='E-mail')
    addr = models.CharField(max_length=500, verbose_name='Адрес')
    working_time = models.CharField(max_length=500, verbose_name='Часы работы')
    instagram_text = models.CharField(max_length=500, verbose_name='Текст instagram')
    instagram_link = models.URLField(max_length=500, verbose_name='Ссылка на аккаунт в instagram')
    development = models.CharField(max_length=500, verbose_name='Компания разработчик')

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return 'Контакты'


class ProjectsPage(SingleInstanceOnly, models.Model):
    services_page_title = models.CharField(max_length=200, verbose_name='Заголовок страницы Projects')
    single_item_top_left_heading = models.CharField(max_length=500, verbose_name='Заголовок в левом верхнем углу')
    single_item_top_right_heading = models.CharField(max_length=500, verbose_name='Заголовок в правом верхнем углу')
    single_item_bottom_left_heading = models.CharField(max_length=500, verbose_name='Заголовок в левом нижнем углу')
    single_item_bottom_right_heading = models.CharField(max_length=500, verbose_name='Заголовок в правом нижнем углу')

    class Meta:
        verbose_name = 'Страница Projects'
        verbose_name_plural = 'Страница Projects'

    def __str__(self):
        return 'Страница проекты'

    def get_random_catalog_items(self, number_of_items):
        return random.sample(list(self.catalogitem_set.filter(show_on_main=True)), number_of_items)


class CatalogItem(models.Model):
    UPLOAD_TO = os.path.join('admin', 'services')

    SERVICE_TYPES = (
        ('design', 'Дизайн'),
        ('house', 'Ремонт квартир и домов'),
        ('office', 'Ремонт офисов'),
        ('construction', 'Строительство домов'),
    )

    service = models.ForeignKey('ProjectsPage', on_delete=models.CASCADE, blank=True)
    show_on_main = models.BooleanField(default=False, verbose_name='Показывать на главной')
    name = models.CharField(max_length=500, verbose_name='Имя')
    type = models.CharField(max_length=80, choices=SERVICE_TYPES, verbose_name='Тип проекта')
    main_img = models.ImageField(upload_to=UPLOAD_TO, blank=True, verbose_name='Главное изображение')
    top_left = models.CharField(max_length=500, verbose_name='Текст в левом верхнем углу')
    top_right = models.CharField(max_length=500, verbose_name='Текст в правом верхнем углу')
    bottom_left = models.CharField(max_length=500, verbose_name='Текст в левом нижнем углу')
    bottom_right = models.CharField(max_length=500, verbose_name='Текст в правом нижнем углу')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def get_absolute_url(self):
        return reverse('main:catalog-item', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.name} - {self.type}'


class CatalogItemImg(models.Model):
    image_field = models.ImageField(upload_to=CatalogItem.UPLOAD_TO, blank=True,
                                    verbose_name='Маленькая картинка на странице services')
    catalog_item = models.ForeignKey('CatalogItem', on_delete=models.CASCADE, blank=False,
                                     verbose_name='Объекты из каталога')
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Картинка айтема каталога'
        verbose_name_plural = 'Картинки айтемов каталога'


class ServicesPage(models.Model):
    title = models.CharField(max_length=500, verbose_name='title')
    heading = models.TextField(max_length=500, verbose_name='Заголовок')
    text_block_left = models.TextField(max_length=1500, verbose_name='Текстовый блок слева')
    text_block_right = models.TextField(max_length=1500, verbose_name='Текстовый блок справа')

    class Meta:
        verbose_name = 'Страница услуги'
        verbose_name_plural = 'Страница услуги'

    def __str__(self):
        return 'Страница сервисы'


class ServicesItem(models.Model):
    SERVICE_TYPE = [
        ['design', 'Дизайн'],
        ['house repair', 'Ремонт квартир и домов'],
        ['office repair', 'Ремонт офисов'],
        ['construction', 'Строительство домов'],
    ]

    UPLOAD_TO = os.path.join('admin', 'index', 'services')

    type = models.CharField(max_length=150, choices=SERVICE_TYPE, verbose_name='Тип услуги')
    name = models.TextField(max_length=500, verbose_name='Название')
    preview_img = models.ImageField(upload_to=UPLOAD_TO, blank=True, verbose_name='Картинка превью')
    main_img = models.ImageField(upload_to=UPLOAD_TO, blank=True, verbose_name='Главная картинка')
    image_text = models.TextField(max_length=500, verbose_name='Текст на картинке')
    projects = models.ManyToManyField('CatalogItem', blank=True, verbose_name='Проекты')
    headings_with_text_blocks = models.ManyToManyField('HeadingAndText', blank=True,
                                                       verbose_name='Заголовки и текст')
    accordion = models.ForeignKey('ServiceItemAccordion', blank=True, on_delete=models.DO_NOTHING,
                                  verbose_name='Аккордион')

    class Meta:
        verbose_name_plural = 'Айтемы услуг'
        verbose_name = 'Айтем услуг'

    def check_enough_headings(self, num):
        print(self.headings_with_text_blocks.count())
        if self.headings_with_text_blocks.count() < num:
            raise ValidationError(
                f'Недостаточно заголовков с текстом для сохранения, добавьте как минимум {num} заголовоков')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:services-item', kwargs={'type': self.type})

    # Можно создать только один инстанс с типом Дизайн/Ремонт квартир/Ремонт офисов etc.
    def save(self, *args, **kwargs):

main/views.py
from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
import json
from django.http import HttpResponse
from django.template.context_processors import csrf
from . import models
from django.views.generic import DetailView, ListView
from . import mixins


# Create your views here.
def index(request):
    context = {
        'index_page': models.IndexPage.objects.first(),
        'contact': models.ContactInfo.objects.first(),
        'service_objects': models.ProjectsPage.objects.first().get_random_catalog_items(3)
    }
    context.update(csrf(request))
    return render_to_response('main/index.html', context=context)


def about(request):
    return render_to_response('main/about.html')


class CatalogView(mixins.ContactInfoMixin, ListView):
    model = models.CatalogItem
    template_name = 'main/catalog.html'
    context_object_name = 'catalog_items'

    def get_queryset(self):
        if 'type' in self.kwargs:
            return get_list_or_404(models.CatalogItem, type=self.kwargs['type'])
        return models.CatalogItem.objects.all()


class ServicesListView(mixins.ContactInfoMixin, ListView):
    model = models.ServicesItem
    template_name = 'main/services_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ServicesListView, self).get_context_data(**kwargs)
        context['services_page'] = models.ServicesPage.objects.first()
        return context


class ServiceItemDetail(mixins.ContactInfoMixin, DetailView):
    model = models.ServicesItem
    template_name = 'main/service_item.html'

    def get_object(self, queryset=None):
        if 'type' in self.kwargs:
            return get_object_or_404(models.ServicesItem, type=self.kwargs['type'])


class ContactsView(mixins.ContactInfoMixin, DetailView):
    model = models.ContactsPage
    template_name = 'main/contacts.html'

    def get_object(self, queryset=None):
        return self.model.objects.first()


class SingleItemView(mixins.ContactInfoMixin, DetailView):
    model = models.CatalogItem
    context_object_name = 'catalog_item'
    template_name = 'main/catalog_item.html'

    def get_context_data(self, **kwargs):
        context = super(SingleItemView, self).get_context_data(**kwargs)
        return context


def mail(request):
    if request.method == 'POST' and request.is_ajax():
        return HttpResponse(json.dumps({'success': 'true'}), content_type="application/json")

main/templates/main/includes/footer.html
<footer class="footer">
    <div class="footer-top">
        <div class="footer-top__inner container">
            <div class="footer-row">
                <div class="footer-row__col">
                    <ul class="footer-list">
                        <li>
                            <a rel="nofollow" class="group text-nowrap" href="tel:{{ contact.phone }}">
                                <i class="icon-phone"></i>
                                <span>{{ contact.phone }}</span>
                            </a>
                        </li>
                        <li>
                            <a rel="nofollow" class="group" href="mailto:{{ contact.email }}">
                                <i class="icon-email"></i>
                                <span>{{ contact.email }}</span>
                            </a>
                        </li>
                        <li>
                            <div class="group">
                                <i class="icon-map-point"></i>
                                <span>{{ contact.addr }}</span>
                            </div>
                        </li>
                    </ul>
                    <ul class="footer-list">
                        <li>
                            <a class="group" href="{{ contact.instagram_link }}" target="_blank" rel="external"
                               title="инстаграм">
                                <i class="icon-instagram"></i>
                                <span>{{ contact.instagram_text }}</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="footer-row__col">
                    <ul class="footer-list footer-list--sm">
                        <li>
                            <a href="{% url 'main:services-item' type='design' %}">Дизайн и проектирование</a>
                        </li>
                        <li>
                            <a href="{% url 'main:services-item' type='house repair' %}">Ремонт квартир и домов</a>
                        </li>
                        <li>
                            <a href="{% url 'main:services-item' type='office repair' %}">Ремонт офисов</a>
                        </li>
                        <li>
                            <a href="{% url 'main:services-item' type='construction' %}">Строительство домов</a>
                        </li>
                        <li>
                            <a href="{% url 'main:catalog' %}">Проекты</a>
                        </li>
                    </ul>
                    <ul class="footer-list footer-list--sm">
                        <li>
                            <a href="{% url 'main:about' %}">О компании</a>
                        </li>
                        <li>
                            <a href="{% url 'main:contacts' %}">Контакты</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bot">
        <div class="footer-bot__inner container">
            <div class="footer-bot__info">
                <div class="footer-bot__copyright"></div>
                <div class="footer-bot__dev">
                    {{ contact.development }}

                </div>
            </div>
            <button class="footer-bot__scrolltop" type="button">
                <i class="icon-up"></i>
            </button>
        </div>
    </div>
</footer>

main/templates/main/includes/header.html
{% load static %}

<header class="header">
    <div class="header__inner container-fluid">
        <div class="header__logo">
            <a href="{% url 'main:index' %}" title="">
                <img src="{% static 'main/img/logo.svg' %}" width="70px">
            </a>
        </div>
    </div>
</header>

main/templates/main/includes/logo.html
{% load static %}

<header class="header">
    <div class="header__inner container-fluid">
        <!--div.header__logo: img(src="media/img/logo.png" alt="")-->
        <div class="header__logo">
            <a href="{% url 'main:index' %}" title="">
                <img src="{% static 'main/img/logo.svg' %}" width="70px">
            </a>
        </div>
    </div>
</header>

main/templates/main/includes/menu.html
<div class="menu-panel">
    <div class="menu-panel__inner">
        <a class="phone" href="tel:{{ contact.phone }}">
            <div class="phone__inner">
                <i class="icon-phone mr-2"></i>
                <span>{{ contact.phone }}</span>
            </div>
        </a>
        <button class="menu" id="menu">
            <div class="menu__icon">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div class="menu__text">
                <div>MENU</div>
            </div>
        </button>
    </div>
</div>

{# active link class is current #}
<nav class="navigation">
    <div class="navigation__inner" id="scroll-container">
        <ul class="nav">
            <li class="nav__item">
                <a class="nav__link" href="{% url 'main:index' %}">
                    Главная
                </a>
            </li>
            <li class="nav__item">
                <a class="nav__link" href="{% url 'main:about' %}">
                    О компании
                </a>
            </li>
            <li class="nav__item">
                <a class="nav__link" href="{% url 'main:catalog' %}">
                    Проекты
                </a>
            </li>
            <li class="nav__item nav__item--has-subnav">
					<span class="nav__link">
						Услуги
						<span class="nav__status"></span>
					</span>
                <div class="subnav">
                    <div class="subnav__item">
                        <a class="subnav__link" href="{% url 'main:services' %}">В раздел</a>
                    </div>
                    <div class="subnav__item">
                        <a class="subnav__link" href="{% url 'main:services-item' type='design' %}">Дизайн
                            и проектирование</a>
                    </div>
                    <div class="subnav__item">
                        <a class="subnav__link" href="{% url 'main:services-item' type='house repair' %}">Ремонт
                            квартир и домов</a>
                    </div>
                    <div class="subnav__item">
                        <a class="subnav__link"
                           href="{% url 'main:services-item' type='office repair' %}">Ремонт офисов</a>
                    </div>
                    <div class="subnav__item">
                        <a class="subnav__link" href="{% url 'main:services-item' type='construction' %}">Строительство
                            домов</a>
                    </div>
                </div>
            </li>
            <li class="nav__item">
                <a class="nav__link" href="{% url 'main:contacts' %}">
                    Контакты
                </a>
            </li>
        </ul>

    </div>
</nav>

main/templates/main/includes/projects-stack.html
{% load reroom_template_tags %}
{% for chunk in items|get_chunks:3 %}
    {% if chunk|length == 1 %}
        <div class="projects-stack">
            <div class="projects-stack__col projects-stack__col--lg">
                <a class="project-card project-card--white-text" data-aos="fade-up"
                   href="{{ chunk.0.get_absolute_url }}">
                    <div class="project-card__img-w">
                        <picture>
                            <source srcset="{{ chunk.0.main_img.url }}"
                                    type="image/webp">
                            <source srcset="{{ chunk.0.main_img.url }}"
                                    type="image/png">
                            <img src="{{ chunk.0.main_img.url }}"/>
                        </picture>

                    </div>
                    <div class="project-card__decor"></div>
                    <div class="project-card__text">
                        <div class="project-card__title">{{ chunk.0.name }}</div>
                        <div class="project-card__subtitle">{{ chunk.0.top_right }}</div>
                    </div>
                </a>
            </div>
        </div>
    {% endif %}
    {% if chunk|length == 2 %}
        2 {{ chunk }}
    {% endif %}


    {% if chunk|length == 3 %}

        <div class="projects-stack">
            {% if forloop.counter|divisibleby:2 %}

                <div class="projects-stack__col">
                    <a class="project-card project-card--sm project-card--black-text"
                       data-aos="fade-up"
                       href="{{ chunk.0.get_absolute_url }}">
                        <div class="project-card__img-w">
                            <picture>
                                <source srcset="{{ chunk.0.main_img.url }}"
                                        type="image/webp">
                                <source srcset="{{ chunk.0.main_img.url }}"
                                        type="image/png">
                                <img src="{{ chunk.0.main_img.url }}"/>
                            </picture>

                        </div>
                        <div class="project-card__decor"></div>
                        <div class="project-card__text">
                            <div class="project-card__title">{{ chunk.0.name }}</div>
                            <div class="project-card__subtitle">{{ chunk.0.top_right }}</div>
                        </div>
                    </a>
                    <a class="project-card project-card--sm project-card--white-text"
                       data-aos="fade-up"
                       href="{{ chunk.1.get_absolute_url }}">
                        <div class="project-card__img-w">
                            <picture>
                                <source srcset="{{ chunk.1.main_img.url }}"
                                        type="image/webp">
                                <source srcset="{{ chunk.1.main_img.url }}"
                                        type="image/png">
                                <img src="{{ chunk.1.main_img.url }}"/>
                            </picture>

                        </div>
                        <div class="project-card__decor"></div>
                        <div class="project-card__text">
                            <div class="project-card__title">{{ chunk.1.name }}</div>
                            <div class="project-card__subtitle">{{ chunk.1.top_right }}</div>
                        </div>
                    </a>
                </div>
                <div class="projects-stack__col projects-stack__col--lg">
                    <a class="project-card project-card--black-text" data-aos="fade-up"
                       href="{{ chunk.2.get_absolute_url }}">
                        <div class="project-card__img-w">
                            <picture>
                                <source srcset="{{ chunk.2.main_img.url }}"
                                        type="image/webp">
                                <source srcset="{{ chunk.2.main_img.url }}"
                                        type="image/png">
                                <img src="{{ chunk.2.main_img.url }}"/>
                            </picture>

                        </div>
                        <div class="project-card__decor"></div>
                        <div class="project-card__text">
                            <div class="project-card__title">{{ chunk.2.name }}</div>
                            <div class="project-card__subtitle">{{ chunk.2.right_top }}</div>
                        </div>
                    </a>
                </div>


            {% else %}


                <div class="projects-stack__col projects-stack__col--lg">
                    <a class="project-card project-card--white-text" data-aos="fade-up"
                       href="{{ chunk.1.get_absolute_url }}">
                        <div class="project-card__img-w">
                            <picture>
                                <source srcset="{{ chunk.0.main_img.url }}"
                                        type="image/webp">
                                <source srcset="{{ chunk.0.main_img.url }}"
                                        type="image/png">
                                <img src="{{ chunk.0.main_img.url }}"
                                     alt="Квартира на&#160;Красногорском бульваре"/>
                            </picture>

                        </div>
                        <div class="project-card__decor"></div>
                        <div class="project-card__text">
                            <div class="project-card__title">{{ chunk.0.name }}</div>
                            <div class="project-card__subtitle">{{ chunk.0.right_top }}</div>
                        </div>
                    </a>
                </div>
                <div class="projects-stack__col">
                    <a class="project-card project-card--sm project-card--black-text"
                       data-aos="fade-up"
                       href="{{ chunk.1.get_absolute_url }}">
                        <div class="project-card__img-w">
                            <picture>
                                <source srcset="{{ chunk.1.main_img.url }}"
                                        type="image/webp">
                                <source srcset="{{ chunk.1.main_img.url }}"
                                        type="image/png">
                                <img src="{{ chunk.1.main_img.url }}"/>
                            </picture>

                        </div>
                        <div class="project-card__decor"></div>
                        <div class="project-card__text">
                            <div class="project-card__title">{{ chunk.1.name }}</div>
                            <div class="project-card__subtitle">{{ chunk.1.right_top }}</div>
                        </div>
                    </a>
                    <a class="project-card project-card--sm project-card--black-text"
                       data-aos="fade-up"
                       href="{{ chunk.2.get_absolute_url }}">
                        <div class="project-card__img-w">
                            <picture>
                                <source srcset="{{ chunk.2.main_img.url }}"
                                        type="image/webp">
                                <source srcset="{{ chunk.2.main_img.url }}"
                                        type="image/png">
                                <img src="{{ chunk.2.main_img.url }}"/>
                            </picture>

                        </div>
                        <div class="project-card__decor"></div>
                        <div class="project-card__text">
                            <div class="project-card__title"> {{ chunk.2.name }} </div>
                            <div class="project-card__subtitle">{{ chunk.2.right_top }}</div>
                        </div>
                    </a>
                </div>


            {% endif %}
        </div>

    {% endif %}
{% endfor %}